#!/usr/lib64/R/bin/Rscript --no-save

library(ORE)
library(ORCH)
ore.connect("BDA","orcl","localhost","welcome1", all=TRUE)
orch.connect("BDA","orcl","localhost","welcome1",secure=F)
ore.sync()
ore.ls()
ore.attach()
myOracleData <- ore.get("ORACLE_CRM")
myNoSQLData <- ore.get("LOADER_NOSQL")
myHDFSData <- ore.get("EXTERNAL_HDFS")
myHiveData <- ore.get("ODI_HIVE")
myOracleData <- ore.get("ORACLE_CRM")
myData <- merge(myNoSQLData, myHiveData, by=c("CUSTOMER_ID"))
myData <- merge(myData, myHDFSData, by=c("CUSTOMER_ID"))
myData <- merge(myData, myOracleData, by=c("CUSTOMER_ID"))
hist(myData$CREDIT_CARD_LIMITS, main = ("Histogram for Credit Card Limit"), plot = TRUE)
myData$CHECKING_AMOUNT <- as.numeric(as.character(myData$CHECKING_AMOUNT))
myData$BANK_FUNDS <- as.numeric(as.character(myData$BANK_FUNDS))
myData$MONTHLY_CHECKS_WRITTEN <- as.numeric(as.character(myData$MONTHLY_CHECKS_WRITTEN))
myData$AMOUNT_AUTOM_PAYMENTS <- as.numeric(as.character(myData$AMOUNT_AUTOM_PAYMENTS))
dt.mod <- ore.odmDT(BUY_INSURANCE ~ ., myData)
summary(dt.mod)
hdfs.put(myData,dfs.name='insur_cust_ltv_sample')
myDataMining <- ore.pull(myData)
library(rpart)
control <- rpart.control(maxdepth = 3)
dectree <- rpart(BUY_INSURANCE ~ BANK_FUNDS + CREDIT_BALANCE + MONEY_MONTLY_OVERDRAWN, data=myDataMining, method = "class", control = control)
summary(dectree)
plot(dectree)
text(dectree)
post(dectree, file="")
ore.create(myData, table="INSUR_CUST_LTV_SAMPLE")
